# 全局信息
title = "TOML格式配置文件示例"
#开发阶段
runmode = "dev"
#请求日志
customLogger = false
#密码干扰码
password_salt ="gou8huo8le8wao8mao8hu8bu8la8lang8li"
# AES-128。key长度：16, 24, 32 bytes 对应 AES-128, AES-192, AES-256
aes_key="Hubu&La_LangLi_WaoMao"

#开发阶段
[stage]
    #开发环境
    [stage.dev]
        #直接取默认用户 true 用于调试，不用每次登陆
        admin_load = true
        #域名
        http = "http://localhost:8080"
    #测试环境
    #生产环境
    [stage.prod]
        #直接取默认用户 true 用于调试，不用每次登陆
        admin_load = false
        #域名
        http = "http://www.hubula.com"
# 网站Cookie Session
[cookieSession]
    #
    sessionon = true
    #
    session_prefix = "_"
    #
    session_name = "ADMIN"
# 应用信息
[app]
    name = "Hubula"
    #只有出现错误时使用
    site_name = "Hubula的博客"
	owner  = ""
    author = "史布斯"
    release = 2021-06-10T08:18:00Z   # 时间
    port = 8080
    #主题
    theme = "av"
    organization = "Mafool"
    mark = "第一行\n第二行."            # 换行

# 网站变量
[webvar]
    #模板目录
    views = "./views"
# 数据库配置
# root:root@tcp(127.0.0.1:3306)/lottery?charset=utf-8
[mysql]
    [mysql.master]
        driverName = "mysql"
        host = "127.0.0.1"
        port = 3306
        user = "root"
        password = "root"
        database = "demo"
        charset = "utf8mb4"
        loc = "Asia%2FShanghai"
        showSql = true
        logLevel = "debug"
        maxIdleConns = 10
        maxOpenConns = 10
        isRunning = true
        parseTime = true
        # connMaxLifetime = 10
        # sslMode = false
    [mysql.slave]
        driverName = "mysql"
        host = "127.0.0.1"
        port = 3306
        user = "root"
        password = "root"
        database = "demo"
        charset = "utf8mb4"
        loc = "Local"
        showSql = true
        logLevel = "debug"
        maxIdleConns = 10
        maxOpenConns = 10
        isRunning = true
        parseTime = true
        # connMaxLifetime = 10
        # sslMode = false

# Redis主从                           # 字典对象
[redis]
    [redis.master]
        host = "10.0.0.1"
        port = 6379
    [redis.slave]
        host = "10.0.0.1"
        port = 6380

# 二维数组
[releases]
release = ["dev", "test", "stage", "prod"]
tags = [["dev", "stage", "prod"],[2.2, 2.1]]


# 公司信息                             #对象嵌套
[company]
    name = "xx科技"
[company.detail]
    type = "game"
    addr = "北京朝阳"
    icp = "030173"
[[song]]
name = "天路"
duration = "4m49s"

[[song]]
name = "忘情水"
duration = "8m03s"

####################################
[upload_default]
#上传方式 local:本地 QiNiu:七牛云存储
type="local"
#允许上传后缀
ext="jpg,gif,png,jpeg"
#上传文件目录
root_path="/uploads/image/"
#临时文件目录
root_path_tmp="/uploads/tmp/"
#最大上传文件大小 5*1024*1024
size=5242880
#是否本地保存
local_save_is=true
#域名,beego 不支持在 配置后注释，还要我变个方法操作
http="#upload_default"

[upload_attachment]
#上传方式 local:本地 QiNiu:七牛云存储
type="local"
#允许上传后缀
ext="jpg,gif,png,jpeg,zip,rar,tar,gz,7z,doc,docx,txt,xml,xlsx,xls"
#上传文件目录
root_path="/uploads/attachment/"
#临时文件目录
root_path_tmp="/uploads/tmp/"
#最大上传文件大小 5*1024*1024
size=5242880
#是否本地保存
local_save_is=true
#域名,beego 不支持在 配置后注释，还要我变个方法操作
http="#upload_attachment"

[qiniu]
access_key="qiniu"
secret_key="qiniu"
#七牛空间
bucket="foxwho"
#七牛根目录，一般默认为空
root_path=""

[csdn]
access_key="csdn"
secret_key="csdn"